server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
#    允许使用ip地址来定义注册中心的地址，默认是false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://127.0.0.1:8761/eureka/
  server:
    enable-self-preservation: false
# 默认情况下，eureka间隔60s将服务清单中没有续约的服务剔除（默认90s内没有续约），本地测试，关闭保护机制，直接让它实时剔除
